//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room_Booking_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_id { get; set; }
        public Nullable<int> Room_no { get; set; }
        public Nullable<System.DateTime> From_date { get; set; }
        public Nullable<System.DateTime> To_date { get; set; }
        public Nullable<int> Total_adults { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PersonId { get; set; }
    
        public virtual RoomDetail RoomDetail { get; set; }
    }
}
