//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room_Booking_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomDetail()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Room_no { get; set; }
        public string Room_type { get; set; }
        public int Bed_quantity { get; set; }
        public string Capacity { get; set; }
        public decimal Amount { get; set; }
        public byte[] Image { get; set; }
        public int Room_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
