//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room_Booking_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableTransaction
    {
        public int Transaction_id { get; set; }
        public string Card_no { get; set; }
        public string Cardholder_name { get; set; }
        public string Card_type { get; set; }
        public int CVV { get; set; }
        public string Expiry_date { get; set; }
        public decimal Amount { get; set; }
    }
}
